{% set name = "fpdb" %}
{% set version = "1.0.3" %}
{% set PYTHON = "/usr/bin/env python" %}
{% set PYTHONVERSION = "3.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: "https://github.com/hnlab/fpdb.git"
    #  sha256: 2c348f41086597fa00896fe76d5618b7180d534eba655da74f4ad8021ca9ba7e

build:
  skip: true # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # - python >={{ PYTHONVERSION }}
    - python 3.6
    - numpy >=1.1.0
    - pip 3.6
    - pbr >=1.0.0
  run:
    - python 3.6
    - h5py >=1.0.0
    - matplotlib >=1.0.0
    - numpy>=1.1.0
    - scipy >=1.1.0

test:
  imports:
    - fpdb

about:
  home: "https://github.com/hnlab/fpdb"
  license: MIT
  license_file: LICENSE 

extra:
  recipe-maintainers:
    - ffallrain


